services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Utilisateur_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
        - postgres:/data/postgres
