services:
  utilisateurdb:
    container_name: Utilisateur-Database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${UTILISATEUR_DB_NAME}'
    env_file: .env
    ports:
      - '${UTILISATEUR_DB_PORT}'
    volumes:
      - ./utilisateurstorage:/data/postgres

  utilisateurms:
    container_name: Utilisateur-MS
    build: 
      context: .
      dockerfile: Dockerfile
    image: 'utilisateurms:latest'
    env_file: .env
    ports:
      - '${SPRING_UTILISATEUR_PORT}:${SPRING_UTILISATEUR_PORT}'