services:
  utilisateur_db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Utilisateur_db'
    env_file: .env
    ports:
      - '${UTILISATEUR_DB_PORT}'
    # volumes:
    #   - utilisateur_db:/data/postgres

  utilisateur_ms:
    image: 'utilisateur_ms:latest'
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${SPRING_UTILISATEUR_PORT}:${SPRING_UTILISATEUR_PORT}'